let config = require("../config.json");
config.aws_sqs_queue = process.env.AWS_SQS_QUEUE || config.aws_sqs_queue
config.execute_interval = process.env.EXECUTE_INTERVAL || config.execute_interval;
config.cursor_name = process.env.CURSOR_NAME || config.cursor_name;
config.fleetplan_queue_uuid = process.env.FLEETPLAN_QUEUE_UUID;
config.mssql.server = process.env.MSSQL_SERVER;
config.mssql.user = process.env.MSSQL_USER;
config.mssql.password = process.env.MSSQL_PASSWORD;
config.mssql.database = process.env.MSSQL_DATABASE;
config.mssql.port = process.env.MSSQL_PORT || config.mssql.port;
config.mssql_sproc_name = process.env.MSSQL_SPROC_NAME;
config.aws_credentials.accessKeyId = process.env.AWS_ACCESS_KEY_ID;
config.aws_credentials.secretAccessKey = process.env.AWS_SECRET_ACCESS_KEY;
module.exports = config;
